import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/AdminShell";
import { OperationForm } from "@/components/admin/OperationForm";
import { PaymentFields } from "@/components/admin/PaymentFields";
import { PrintButton } from "@/components/admin/PrintButton";
import { addOrderMaterial, recordPayment, removeOrderMaterial, updateServiceOrder, voidPayment } from "@/lib/admin/operations-actions";
import { canSeeFinance, canWrite, requireAdmin } from "@/lib/admin/auth";
import { getInventory, getServiceOrder, getStaff } from "@/lib/admin/operations";
import { dateTime, money, orderStatusLabel } from "@/lib/admin/operations-types";

export const dynamic = "force-dynamic";

export default async function WorkOrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const admin = await requireAdmin();
  const { id } = await params;
  const [result, inventoryResult, staffResult] = await Promise.all([getServiceOrder(id), getInventory(), getStaff()]);
  if (!result.data) notFound();
  const { order, materials, payments, audit } = result.data;
  const finance = canSeeFinance(admin.role);
  const remaining = Math.max(0, Number(order.grand_total) - Number(order.paid_amount));
  return (
    <AdminShell>
      <div className="mb-6 flex flex-wrap items-start justify-between gap-4">
        <div><Link href="/admin/work-orders" className="text-sm font-semibold text-blue-700">← Listeye dön</Link><h1 className="mt-2 text-3xl font-bold">{order.order_number}</h1><p className="text-slate-500">{order.customer?.name} · {order.service_name} · {orderStatusLabel(order.status)}</p></div>
        <div className="flex flex-wrap gap-2"><a className="btn btn-secondary" href={`tel:${order.customer?.primary_phone}`}>Telefonla Ara</a><a className="btn btn-secondary" href={`https://wa.me/${String(order.customer?.primary_phone ?? "").replace(/\D/g, "")}`} target="_blank" rel="noreferrer">WhatsApp</a><PrintButton /></div>
      </div>
      {finance ? <section className="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 shadow-sm sm:p-5">
        <div className="mb-4 flex flex-wrap items-start justify-between gap-3">
          <div><p className="text-sm font-bold text-emerald-800">Borç Ödeme / Tahsilat Al</p><h2 className="mt-1 text-xl font-bold text-slate-950">{order.customer?.name} için kalan borç: {money(remaining, order.currency)}</h2><p className="mt-1 text-sm text-slate-600">Ödemeyi bu ekrandan kaydedin; bakiye ve iş emri anında güncellenir.</p></div>
          {remaining <= 0.01 ? <span className="status-badge bg-emerald-100 text-emerald-800">Borç kapandı</span> : null}
        </div>
        {remaining > 0.01 ? <OperationForm action={recordPayment} submitLabel="Ödemeyi Kaydet" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><input type="hidden" name="customer_id" value={order.customer_id} /><input type="hidden" name="service_order_id" value={order.id} /><input type="hidden" name="exchange_rate" value={order.exchange_rate ?? ""} /><input type="hidden" name="exchange_rate_date" value={(order as unknown as { exchange_rate_date?: string }).exchange_rate_date ?? ""} /><input type="hidden" name="idempotency_key" value={crypto.randomUUID()} />
          <div className="admin-field"><label htmlFor="paid_at">Ödeme tarihi</label><input id="paid_at" name="paid_at" type="datetime-local" defaultValue={new Date().toISOString().slice(0,16)} /></div><PaymentFields remaining={remaining} currency={order.currency} exchangeRate={order.exchange_rate} />
          <div className="admin-field"><label htmlFor="method">Yöntem</label><select id="method" name="method"><option value="cash">Nakit</option><option value="credit_card">Kredi Kartı</option><option value="bank_transfer">Banka Havalesi</option><option value="eft">EFT</option><option value="check">Çek</option><option value="other">Diğer</option></select></div><div className="admin-field"><label htmlFor="collected_by">Tahsil eden</label><select id="collected_by" name="collected_by"><option value="">Seçin</option>{staffResult.data.map((s) => <option key={s.id} value={s.id}>{s.full_name}</option>)}</select></div><div className="admin-field"><label htmlFor="reference_number">Referans</label><input id="reference_number" name="reference_number" /></div><div className="admin-field sm:col-span-2"><label htmlFor="payment_description">Açıklama</label><textarea id="payment_description" name="description" /></div>
        </OperationForm> : null}
      </section> : null}
      <nav className="mb-5 flex gap-2 overflow-x-auto print:hidden">{["genel", "malzemeler", "odemeler", "gecmis"].map((tab) => <a href={`#${tab}`} className="btn btn-ghost shrink-0" key={tab}>{({ genel: "Genel Bilgiler", malzemeler: "Malzemeler", odemeler: "Ödemeler & Tahsilat", gecmis: "İşlem Geçmişi" } as Record<string, string>)[tab]}</a>)}</nav>
      {finance ? <div className="admin-grid mb-6"><div className="admin-card"><p className="text-sm text-slate-500">Toplam Maliyet</p><strong>{money(order.total_cost, order.currency)}</strong></div><div className="admin-card"><p className="text-sm text-slate-500">Müşteri Toplamı</p><strong>{money(order.grand_total, order.currency)}</strong></div><div className="admin-card"><p className="text-sm text-slate-500">Kalan Bakiye</p><strong>{money(remaining, order.currency)}</strong></div><div className="admin-card"><p className="text-sm text-slate-500">Net Kâr</p><strong>{money(order.net_profit, order.currency)}</strong></div></div> : null}

      <section id="genel" className="admin-card scroll-mt-36"><h2 className="mb-4 text-xl font-bold">Genel Bilgiler</h2>
        {canWrite(admin.role) ? <OperationForm action={updateServiceOrder} submitLabel="İş Emrini Güncelle" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><input type="hidden" name="id" value={order.id} />
          <div className="admin-field"><label htmlFor="status">Servis durumu</label><select id="status" name="status" defaultValue={order.status}><option value="draft">Taslak</option><option value="started">İşlem Başladı</option><option value="waiting_material">Malzeme Bekleniyor</option><option value="completed">Tamamlandı</option><option value="cancelled">İptal Edildi</option></select></div>
          <div className="admin-field"><label htmlFor="labor_hours">İşçilik süresi (saat)</label><input id="labor_hours" name="labor_hours" type="number" min="0" step="0.25" defaultValue={(order as unknown as { labor_hours: number }).labor_hours} /></div>
          {finance ? <><div className="admin-field"><label htmlFor="labor_cost">İşçilik maliyeti</label><input id="labor_cost" name="labor_cost" type="number" min="0" step="0.01" defaultValue={(order as unknown as { labor_cost: number }).labor_cost} /></div><div className="admin-field"><label htmlFor="labor_sale">Hizmet satış tutarı</label><input id="labor_sale" name="labor_sale" type="number" min="0" step="0.01" defaultValue={order.labor_sale} /></div><div className="admin-field"><label htmlFor="transport_cost">Ulaşım gideri</label><input id="transport_cost" name="transport_cost" type="number" min="0" step="0.01" defaultValue={(order as unknown as { transport_cost: number }).transport_cost} /></div><div className="admin-field"><label htmlFor="extra_staff_cost">Ek personel maliyeti</label><input id="extra_staff_cost" name="extra_staff_cost" type="number" min="0" step="0.01" defaultValue={(order as unknown as { extra_staff_cost: number }).extra_staff_cost} /></div><div className="admin-field"><label htmlFor="other_cost">Diğer giderler</label><input id="other_cost" name="other_cost" type="number" min="0" step="0.01" defaultValue={(order as unknown as { other_cost: number }).other_cost} /></div><div className="admin-field"><label htmlFor="discount">İndirim</label><input id="discount" name="discount" type="number" min="0" step="0.01" defaultValue={(order as unknown as { discount: number }).discount} /></div><div className="admin-field"><label htmlFor="tax_rate">Vergi oranı (%)</label><input id="tax_rate" name="tax_rate" type="number" min="0" max="100" step="0.01" defaultValue={order.tax_rate} /></div></> : null}
          <div className="admin-field sm:col-span-2"><label htmlFor="technician_note">Teknik personel notu</label><textarea id="technician_note" name="technician_note" defaultValue={(order as unknown as { technician_note: string | null }).technician_note ?? ""} /></div><div className="admin-field"><label htmlFor="customer_note">Müşteri notu</label><textarea id="customer_note" name="customer_note" defaultValue={(order as unknown as { customer_note: string | null }).customer_note ?? ""} /></div>
        </OperationForm> : <p>Salt görüntüleme yetkisi.</p>}
      </section>

      <section id="malzemeler" className="admin-card mt-5 scroll-mt-36"><h2 className="mb-4 text-xl font-bold">Malzemeler</h2>
        <div className="admin-mobile-list mb-5">{materials.map((m) => <article className="admin-mobile-item" key={m.id}><h3 className="font-bold text-slate-950">{m.name}</h3><p className="mt-1 text-sm text-slate-500">{m.brand} {m.model} · {m.supplier_name ?? "Tedarikçi yok"}</p><dl className="admin-mobile-metrics"><div><dt>Miktar</dt><dd>{m.quantity} {m.unit}</dd></div><div><dt>Seri no</dt><dd>{m.serial_number ?? "—"}</dd></div><div className="col-span-2"><dt>Garanti</dt><dd>{m.warranty_end_date ? `Garanti: ${m.warranty_end_date}` : "Garanti bilgisi yok"}</dd></div>{finance ? <><div><dt>Maliyet</dt><dd>{money(m.total_purchase_cost, "TRY")}</dd></div><div><dt>Satış</dt><dd>{money(m.total_sale_price, order.currency)}</dd></div></> : null}</dl>{canWrite(admin.role) ? <OperationForm action={removeOrderMaterial} submitLabel="Malzemeyi Geri Al" className="mt-3"><input type="hidden" name="service_order_id" value={order.id} /><input type="hidden" name="material_row_id" value={m.id} /></OperationForm> : null}</article>)}</div>
        <div className="mb-5 hidden sm:block"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Malzeme</th><th>Miktar</th><th>Seri / Garanti</th>{finance ? <><th>Maliyet</th><th>Satış</th></> : null}<th /></tr></thead><tbody>{materials.map((m) => <tr key={m.id}><td><strong>{m.name}</strong><br /><span className="text-xs">{m.brand} {m.model} · {m.supplier_name}</span></td><td>{m.quantity} {m.unit}</td><td>{m.serial_number ?? "—"}<br />{m.warranty_end_date ? `Garanti: ${m.warranty_end_date}` : "Garanti bilgisi yok"}</td>{finance ? <><td>{money(m.total_purchase_cost, "TRY")}</td><td>{money(m.total_sale_price, order.currency)}</td></> : null}<td>{canWrite(admin.role) ? <OperationForm action={removeOrderMaterial} submitLabel="Geri Al" className="space-y-2"><input type="hidden" name="service_order_id" value={order.id} /><input type="hidden" name="material_row_id" value={m.id} /></OperationForm> : null}</td></tr>)}</tbody></table></div></div>
        {canWrite(admin.role) ? <OperationForm action={addOrderMaterial} submitLabel="Malzemeyi Ekle" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><input type="hidden" name="service_order_id" value={order.id} />
          <div className="admin-field lg:col-span-2"><label htmlFor="material_id">Stoktan seç (opsiyonel)</label><select id="material_id" name="material_id"><option value="">Harici / stoksuz malzeme</option>{inventoryResult.data.map((m) => <option value={m.id} key={m.id}>{m.name} · Stok {m.stock_quantity} {m.unit}</option>)}</select></div>
          <div className="admin-field lg:col-span-2"><label htmlFor="material_name">Malzeme adı</label><input id="material_name" name="name" /></div>
          <div className="admin-field"><label htmlFor="category">Kategori</label><input id="category" name="category" /></div><div className="admin-field"><label htmlFor="brand">Marka</label><input id="brand" name="brand" /></div><div className="admin-field"><label htmlFor="model">Model</label><input id="model" name="model" /></div><div className="admin-field"><label htmlFor="serial_number">Seri numarası</label><input id="serial_number" name="serial_number" /></div>
          <div className="admin-field"><label htmlFor="quantity">Miktar</label><input id="quantity" name="quantity" type="number" min="0.001" step="0.001" defaultValue="1" required /></div><div className="admin-field"><label htmlFor="unit">Birim</label><input id="unit" name="unit" defaultValue="adet" /></div>
          {finance ? <><div className="admin-field"><label htmlFor="unit_purchase_price">Birim alış fiyatı</label><input id="unit_purchase_price" name="unit_purchase_price" type="number" min="0" step="0.01" /></div><div className="admin-field"><label htmlFor="unit_sale_price">Birim satış fiyatı</label><input id="unit_sale_price" name="unit_sale_price" type="number" min="0" step="0.01" /></div></> : null}
          <div className="admin-field"><label htmlFor="supplier_name">Tedarikçi</label><input id="supplier_name" name="supplier_name" /></div><div className="admin-field"><label htmlFor="purchase_date">Alış tarihi</label><input id="purchase_date" name="purchase_date" type="date" /></div><div className="admin-field"><label htmlFor="document_number">Fatura / irsaliye</label><input id="document_number" name="document_number" /></div><div className="admin-field"><label htmlFor="warranty_months">Garanti (ay)</label><input id="warranty_months" name="warranty_months" type="number" min="0" /></div><div className="admin-field"><label htmlFor="warranty_start_date">Garanti başlangıcı</label><input id="warranty_start_date" name="warranty_start_date" type="date" /></div>
        </OperationForm> : null}
      </section>

      <section id="odemeler" className="admin-card mt-5 scroll-mt-36"><h2 className="mb-4 text-xl font-bold">Ödeme Geçmişi</h2>
        {payments.map((p) => <div key={p.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 py-2 text-sm"><p>{dateTime(p.paid_at)} · <strong>{money(p.amount, p.currency)}</strong> · {p.method} · {p.collector?.full_name ?? "—"}</p>{finance ? <OperationForm action={voidPayment} submitLabel="Tahsilatı İptal Et" className="space-y-2"><input type="hidden" name="service_order_id" value={order.id} /><input type="hidden" name="payment_id" value={p.id} /></OperationForm> : null}</div>)}
        {payments.length === 0 ? <p className="text-sm text-slate-500">Henüz tahsilat kaydı yok.</p> : null}
      </section>

      <section id="gecmis" className="admin-card mt-5 scroll-mt-36"><h2 className="mb-4 text-xl font-bold">İşlem Geçmişi</h2>{audit.length ? audit.map((item) => <p key={item.id} className="border-b py-2 text-sm">{dateTime(item.created_at)} · {item.action} · {item.target_table}</p>) : <p className="text-sm text-slate-500">İşlem geçmişi yok.</p>}</section>
    </AdminShell>
  );
}
